version: 0.2

phases:
  install:
      commands:
        - echo "installing something"
  pre_build:
     commands:
       - echo "We are in the pre-build phase"
  build:
     commands:
       - echo "we are in the build block"
  post_build:
     commands:
      - echo "We are in the post_build  phase."
